# Generated by Django 3.2.16 on 2023-01-19 06:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_content_dynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog-pics')),
                ('topic_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('topic_abstract', models.CharField(blank=True, max_length=500, null=True)),
                ('topic_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='career_content_dynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_post', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('job_department', models.CharField(blank=True, max_length=500, null=True)),
                ('job_requirements', models.TextField(blank=True, null=True)),
                ('job_years_exp', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
