# Generated by Django 3.2.16 on 2023-01-19 07:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog_content_dynamic_career_content_dynamic'),
    ]

    operations = [
        migrations.AddField(
            model_name='career_content_dynamic',
            name='job_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='career_content_dynamic',
            name='job_responsibilities',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='career_content_dynamic',
            name='job_requirements',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
